# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty

branches:
  only:
    - master

env:
  global:
    secure: "KbxZXwF51qTGVz53pYCd6jfgwIL3cjr9RqW4QKV7M6JnwbytBB8E66x747UO/KFQStL6DKKnkp5OoEWRMq9LL97VnM1GuIKOe39IpANIgSZDnO22pWoSM85KNQEFFl04bLTbarR41XFc704oxpVb7bd2t15cyBL1SUDlSHhauv4="

matrix:
  include:
    - env: PYTHON=2.7 CONDA_PY=27 QT_VERSION=4
    - env: PYTHON=3.4 CONDA_PY=34 QT_VERSION=4
    - env: PYTHON=3.5 CONDA_PY=35 QT_VERSION=5
    - env: PYTHON=3.6 CONDA_PY=36 QT_VERSION=5

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda install conda-build anaconda-client --yes -q
  - conda config --add channels ecpy
  - conda create -n travisci --yes python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install --yes -q"
  - PIP_INSTALL="pip install -q"

  # Setup conda build output directory
  - cd ~
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)

  # Install ecpy dependencies
  - $CONDA_INSTALL pyqt=$QT_VERSION future numpy configobj watchdog enaml qtawesome
  - $PIP_INSTALL pyvisa

  # Intall test tools
  - $CONDA_INSTALL pytest
  - $PIP_INSTALL pytest-cov pytest-catchlog pytest-timeout
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/enaml_coverage_plugin/tarball/master

  # Install codecov report tools
  - $PIP_INSTALL codecov

install:

  # Install ecpy (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - conda build conda -q  # Package building does run only very minimal tests)
  - conda install ecpy --use-local --yes -q --override-channels
  - cd ~

before_script:
# I need a (fake) display on Travis so I need to start a X server.
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Run the Ecpy test suite
  - cd $TRAVIS_BUILD_DIR
  - export QT_API=pyqt$QT_VERSION
  - py.test tests --cov ecpy --cov-report xml -v

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - codecov
  - export PACK="$(conda build conda --output)"
  - conda convert $PACK -p 'all' --quiet -o $CONDA_BLD_PATH
  - cd $CONDA_BLD_PATH
  - source deactivate
  - if [[ $TRAVIS_SECURE_ENV_VARS ]]; then python ../continuous-integration/anaconda-push.py; fi
