# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=3.5 CONDA_PY=35 QT_VERSION=5
    - env: PYTHON=3.6 CONDA_PY=36 QT_VERSION=5

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda config --set always_yes yes
  - conda config --append channels exopy
  - conda install conda-build anaconda-client -q
  - conda info -a
  - conda create -n travisci python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install -q"
  - PIP_INSTALL="pip install -q"

  # Setup conda build output directory
  - cd ~
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)

  # Install exopy dependencies
  - $CONDA_INSTALL pyqt=$QT_VERSION numpy configobj watchdog enaml>=0.10.2 qtawesome pyvisa

  # Intall test tools
  - $CONDA_INSTALL pytest
  - $PIP_INSTALL pytest-cov pytest-timeout pytest-qt
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/enaml_coverage_plugin/tarball/master

  # Install codecov report tools
  - $PIP_INSTALL codecov

install:

  # Build exopy conda package and install it (check that build script is not broken)
  - cd $TRAVIS_BUILD_DIR
  - conda build conda -q  # Package building does run only very minimal tests
  - conda install exopy --use-local -q
  - cd ~

before_script:
# I need a (fake) display on Travis so I need to start a X server.
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Run the Exopy test suite
  - cd ~
  - export COVERAGE_DATAFILE=$TRAVIS_BUILD_DIR/.coverage
  - export QT_API=pyqt$QT_VERSION
  - "pytest $TRAVIS_BUILD_DIR/tests -v --log-cli-level CRITICAL --cov exopy --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov-config $TRAVIS_BUILD_DIR/.coveragerc"

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then bash continuous-integration/deploy.sh; fi
