package:
  name: exopy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
              )}}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - exopy = exopy.__main__:main
  osx_is_app: True

requirements:
  host:
    - python >=3.5
    - pyqt >=5 # Add PyQt so that it does not appear in the package requires
               # which avoids issues when extension packages depending on exopy
               # check that all their dependencies are present.
  run:
    - python >=3.5
    - python.app       [osx]
    - enaml >=0.10.2
    - pyqt >=5
    - atom >=0.4.1
    - kiwisolver >=1.0.0
    - watchdog
    - configobj
    - qtawesome
    - numpy

test:
  commands:
    - exopy --help
  imports:
    - exopy

app:
  entry: exopy
  summary: 'Exopy application'

about:
  home: https://github.com/Exopy/exopy
  license: BSD
  license_file: LICENSE
  summary: High level experiment automation program
