package:
  name: ecpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - ecpy = ecpy.__main__:main
  osx_is_app: True
  has_prefix_files:
    - ecpy/*.enamlc

requirements:
  build:
    - python
    - future
    - enaml >=0.10.2.dev
  run:
    - python
    - python.app       [osx]
    - enaml >=0.10.2.dev
    - pyqt
    - atom >=0.4.0.dev
    - kiwisolver >=0.2.0.dev
    - future
    - watchdog
    - configobj
    - qtawesome
    - numpy

test:
  commands:
    - ecpy --help
  imports:
    - ecpy

app:
  entry: ecpy
  summary: 'Ecpy application'

about:
  home: https://github.com/Ecpy/ecpy
  license: BSD
  license_file: LICENSE
  summary: High level experiment automation program
