name: Continuous Integration
on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - "exopy/**"
      - "tests/**"
      - setup.py

jobs:
  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - name: Install linux only test dependency
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        # Install all dependencies needed to run Qt on linux (taken from the qt website
        # and completed by adding package marked missing when running with
        # QT_DEBUG_PLUGINS=1)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libfontconfig1-dev libfreetype6-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-x11-dev libxcb-xtest0-dev  libegl1-mesa xvfb matchbox-window-manager --fix-missing
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install project
        run: |
          python setup.py develop
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov pytest-qt
          python -m pip install https://github.com/MatthieuDartiailh/enaml_coverage_plugin/tarball/master
      - name: Run tests (Windows)
        if: matrix.os != 'ubuntu-latest'
        run: python -X dev -m pytest tests --cov enaml --cov-report xml
      - name: Run tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          export DISPLAY=:99.0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
          sleep 3
          matchbox-window-manager &
          sleep 1
          python -X dev -m pytest tests --cov exopy --cov-report xml -v --log-cli-level CRITICAL

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os != 'windows-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
