name: Continuous Integration
on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - "exopy/**"
      - "tests/**"
      - setup.py

jobs:
  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel pyqt5
      - name: Install project
        run: |
          python setup.py develop
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov pytest-qt pytest-timeout
          python -m pip install https://github.com/MatthieuDartiailh/enaml_coverage_plugin/tarball/master
      - name: Run tests (Windows)
        if: matrix.os != 'ubuntu-latest'
        run: python -X dev -m pytest tests --cov enaml --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os != 'windows-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
